version: "3.3"
services:
  amidanotemysql:
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: ZjP68Ygd
      MYSQL_ROOT_PASSWORD: ZjP68Ygd
    ports:
      - "8024:3306"
    expose:
      - "3306"
    volumes:
      - "/media/ken/AppDisk1/apps/amidanote.com/data/mysql:/var/lib/mysql"
