version: "3.3"
services:
  mysql:
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: ZjP68Ygd
      MYSQL_ROOT_PASSWORD: ZjP68Ygd
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "docudocu-db:/var/lib/mysql"
  mysql-test:
    image: "mysql:8.0"
    restart: always
    environment:
      MYSQL_DATABASE: dbtest
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: testtest
      MYSQL_ROOT_PASSWORD: testtest
    ports:
      - "3307:3306"
    expose:
      - "3307"
    volumes:
      - "docudocu-db-test2:/var/lib/mysql"
volumes:
  docudocu-db:
  docudocu-db-test2:
